# The configuration below configured Travis to run for CI/CD
# Sudo required for install awscli and python
sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
python:
  - "3.5"
cache:
  directories:	
    - node_modules
install:
  # awscli is required to create CloudFront invalidation rule 
  - pip install --user awscli
before_script:
  - npm install
  - yarn
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  local_dir: build
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"